# Combine features with functions

In [1]:
import pandas as pd
from feature_engine.creation import MathFeatures
from sklearn.datasets import load_breast_cancer

In [2]:
# load the breast cancer dataset from sklearn
data = load_breast_cancer()

# create a dataframe with the independent variables
df = pd.DataFrame(data.data, columns=data.feature_names)

df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [3]:
# # print description of dataset

# print(data.DESCR)

In [4]:
# make a list with the features we want to combine

features = [
    "mean smoothness",
    "mean compactness",
    "mean concavity",
    "mean concave points",
    "mean symmetry",
]

In [5]:
df[features].head()

,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry
0,0.11840,0.27760,0.3001,0.14710,0.2419
1,0.08474,0.07864,0.0869,0.07017,0.1812
2,0.10960,0.15990,0.1974,0.12790,0.2069
3,0.14250,0.28390,0.2414,0.10520,0.2597
4,0.10030,0.13280,0.1980,0.10430,0.1809

In [6]:
# take the average

df["mean_features"] = df[features].mean(axis=1)

df["mean_features"].head()

0    0.21702
1    0.10033
2    0.16034
3    0.20654
4    0.14326
Name: mean_features, dtype: float64

In [7]:
# calculate the standard deviation

df["std_features"] = df[features].std(axis=1)

df["std_features"].head()

0    0.080321
1    0.045671
2    0.042333
3    0.078097
4    0.044402
Name: std_features, dtype: float64

In [8]:
# list with functions to apply for combinations

math_func = ["sum", "prod", "mean", "std", "max", "min"]

In [9]:
# Perform all the operations in one line

df_t = df[features].agg(math_func, axis="columns")

df_t.head()

       sum      prod     mean       std     max      min
0  1.08510  0.000351  0.21702  0.080321  0.3001  0.11840
1  0.50165  0.000007  0.10033  0.045671  0.1812  0.07017
2  0.80170  0.000092  0.16034  0.042333  0.2069  0.10960
3  1.03270  0.000267  0.20654  0.078097  0.2839  0.10520
4  0.71630  0.000050  0.14326  0.044402  0.1980  0.10030

In [10]:
# name of new features

new_feature_names = ["sum_f", "prod_f", "mean_f", "std_f", "max_f", "min_f"]

In [11]:
# automate feature combination with Feature-engine

create = MathFeatures(
    variables=features,
    func=math_func,
    new_variables_names=new_feature_names,
)

In [12]:
# combine features

df_t = create.fit_transform(df)

In [13]:
df_t[features + new_feature_names].head()

,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,sum_f,prod_f,mean_f,std_f,max_f,min_f
0,0.11840,0.27760,0.3001,0.14710,0.2419,1.08510,0.000351,0.21702,0.080321,0.3001,0.11840
1,0.08474,0.07864,0.0869,0.07017,0.1812,0.50165,0.000007,0.10033,0.045671,0.1812,0.07017
2,0.10960,0.15990,0.1974,0.12790,0.2069,0.80170,0.000092,0.16034,0.042333,0.2069,0.10960
3,0.14250,0.28390,0.2414,0.10520,0.2597,1.03270,0.000267,0.20654,0.078097,0.2839,0.10520
4,0.10030,0.13280,0.1980,0.10430,0.1809,0.71630,0.000050,0.14326,0.044402,0.1980,0.10030